[[README.md]]
== Fiches moto pour le permis A2

Après avoir cherché quelques temps une source fiable sur internet, j’ai
fini par prendre
https://www.legifrance.gouv.fr/affichTexte.do?cidTexte=JORFTEXT000025803553[l’arrêté
publié au journal officiel] (et sa
http://www.legifrance.gouv.fr/jopdf/common/jo_pdf.jsp?numJO=0&dateJO=20140411&numTexte=11&pageDebut=06585&pageFin=06617[version
pdf avec les schémas]) et d’en faire quelques fiches récapitulatives.

Note: dans le texte officiel, les chiffres clés datent de 2011, ie. ``A
kilométrage égal un conducteur de moto a 20 fois plus de risque d’être
tué qu’un automobiliste''. Vous trouverez peut être des chiffres plus
récent en révisant sur livret papier (``A kilométrage égal un conducteur
de moto a *23 fois* plus de risque d’être tué qu’un automobiliste''),
ils restent très similaires, pas importants lors de l’examen.

=== Vérifications techniques

L’expert interroge le candidat en choisissant un sujet de vérification
pour chacun de ces thèmes :

* les commandes,
* les éléments techniques,
* l’éclairage et les accessoires de sécurité.

link:#verifications-techniques.md[Vérifications techniques]

=== Fiches pour interrogations orales

Fiches de révisions complètes avec les points principaux, le résumé des
chiffres.

* link:#fiche-1.md[Fiche 1 : Le risque routier moto/comportement en
présence d’un accident]
* link:#fiche-2.md[Fiche 2 : Les accidents les plus caractéristiques]
* link:#fiche-3.md[Fiche 3 : Les facteurs de risque à moto]
* link:#fiche-4.md[Fiche 4 : Prise de conscience des risques]
* link:#fiche-5.md[Fiche 5 : La conduite préventive]
* link:#fiche-6.md[Fiche 6 : L’équipement]
* link:#fiche-7.md[Fiche 7 : Les éléments mécaniques du motocycle liés à
la sécurité]
* link:#fiche-8.md[Fiche 8 : L’assurance]
* link:#fiche-9.md[Fiche 9 : L’alcool, les stupéfiants]
* link:#fiche-10.md[Fiche 10 : La fatigue et la route de nuit]
* link:#fiche-11.md[Fiche 11 : Vitesse et freinage]
* link:#fiche-12.md[Fiche 12 : Stabilité et trajectoire]

=== Fiches d’interrogation examen

Les points principaux pour chaque fiche, lors de l’interrogation orale,
vous devez développer autour de chaque point :

link:#fiches-interrogations.md[Les 12 fiches d’interrogations]

[[fiche-1.md]]
== Le risque routier moto/comportement en présence d’un accident

=== Le risque routier à moto

* Les motocyclistes représentent moins de 2 % du trafic mais près de 20
% des tués.
* Ils sont impliqués dans près d’un accident corporel sur quatre.

Cela représente pour la seule année 2011 (Source ONISR) :

* 6 200 blessés hospitalisés.
* 760 décès.
* A kilométrage égal un conducteur de moto a 20 fois plus de risque
d’être tué qu’un automobiliste.

Les motocyclistes morts sur la route:

* Un tiers meurt dans des accidents sans autre usager impliqué.
* 2 décès sur 3 ont lieu en rase campagne.
* Dans 9 cas sur 10 sur route sèche.
* 93 % des tués sont des hommes.
* 1 motocycliste tué sur 5 a moins de 25 ans.

C’est dans les six premiers mois après l’obtention du permis, ou dans
les six premiers mois de reprise de la moto après une longue
interruption de pratique que le risque d’accident mortel à moto est le
plus élevé.

=== Gravité

Du fait de l’absence d’une carrosserie, le motocycliste ne bénéficie
d’aucune protection. En conséquence, il existe un risque corporel à
chaque accident, à chaque accrochage. De plus, la gravité de l’accident
est fonction de la vitesse, or les vitesses pratiquées par les
motocyclistes sont nettement supérieures à celles pratiquées par les
automobilistes.

Ainsi, de nombreux blessés sont susceptibles de garder des séquelles
invalidantes. Parmi les lésions les plus graves on trouve :

* la tête (lésions cérébrales : traumatisme crânien).
* les membres inférieurs (lésions orthopédiques avec amputation d’un
membre parfois).
* la colonne vertébrale (les lésions de la moelle épinière : paraplégie
ou tétraplégie).

=== Comportement en présence d’un accident

Les gestes d’urgence :

* Protéger : signaler l’accident aux autres usagers pour éviter un sur
accident. De nuit essayer d’éclairer l’accident.
* Alerter : police ou gendarmerie (numéro d’urgence européen : 112),
lorsqu’on arrive le premier le plus rapidement. Sinon passer avec
prudence pour ne pas encombrer inutilement les lieux.
* Secourir : couvrir les blessés, leur parler mais ne pas intervenir
sans compétences spécialisées.

Les gestes dangereux :

* Donner à boire à un blessé.
* Déplacer un blessé (sauf nécessité immédiate : incendie…).
* Enlever son casque à un motocycliste.

[[fiche-2.md]]
== Les accidents les plus caractéristiques

=== Accidents en collision

Ils sont les plus fréquents et souvent les plus graves car l’énergie
cinétique libérée est bien plus importante que lors d’un choc contre un
obstacle fixe.

Un choc à 50 km/h contre obstacle fixe équivaut déjà à une chute de 3
étages.

Mais un choc frontal à 50 km/h contre un autre véhicule roulant à 50
km/h est comparable à un choc à 100 km/h contre obstacle fixe, soit une
chute d’une douzaine d’étages.

Les collisions sont dues essentiellement au fait que les autres usagers
(les automobilistes en particulier) détectent difficilement les
motocyclistes.

La nature même d’une moto, son faible gabarit notamment et sa forte
capacité d’accélération sont des caractéristiques d’ensemble qui ne
favorisent pas une bonne détection.

Dans ce type d’accident, il ressort principalement de la part des
motocyclistes :

* une faible expérience de la conduite.
* un attachement trop rigide au statut prioritaire.
* une vitesse inadaptée à la situation.

Les plus caractéristiques :

[arabic]
. En intersection : automobiliste non prioritaire qui souhaite s’insérer
dans le trafic : il ne détecte pas le motocycliste ou apprécie mal sa
vitesse et lui coupe la route.
. Circulation du motocycliste sur un axe prioritaire, un automobiliste
arrive en face et change de direction : il ne détecte pas le
motocycliste ou apprécie mal sa vitesse et lui coupe la route.
. Manœuvre de dépassement effectuée par le motocycliste quand
l’automobiliste décide au même moment de tourner à gauche : il ne
détecte pas le motocycliste et lui coupe la route.
. Collision par le motocycliste d’un autre usager à l’arrêt : non
respect des distances de sécurité, inattention ou excès de confiance
dans la phase de freinage.
. Collision par un autre usager du motocycliste à l’arrêt : motocycliste
perçu trop tard par l’automobiliste.
. Choc frontal : dépassement mal anticipé, non respect des vitesses ou
mauvaise visibilité.

=== Accidents en solo

En dehors des accidents liés à l’alcool ou à l’usage de stupéfiants il
s’agit principalement d’un mauvais contrôle du véhicule en situation de
négociation de trajectoire et de la mauvaise évaluation des difficultés
routières rencontrées (travaux, virage mal apprécié…).

Dans ce type d’accident il ressort de la part des motocyclistes :

* une faible expérience de la conduite et du véhicule.
* une vitesse trop élevée pour gérer une difficulté imprévue.
* l’adoption d’une conduite à risque (ludique, compétitive, test d’un
véhicule ou transgression caractérisée).

Si les ``erreurs'' de conduite ne sont pas plus fréquentes chez les
motocyclistes, elles sont moins récupérables et leurs conséquences
souvent dramatiques.

Les plus caractéristiques :

[arabic]
. Vitesse trop élevée en entrée de virage avec perte de contrôle : chute
après rencontre avec un obstacle fixe, ou chute par perte d’adhérence
(moto trop inclinée, revêtement soudainement glissant).
. Perte d’adhérence au freinage : manque de maîtrise du véhicule.
. Guidonnage en ligne droite : peut être dû au revêtement de chaussée
mais le plus souvent à un défaut d’entretien du véhicule.
. Perte de contrôle suite à un écart dû à la présence d’un animal, à une
mauvaise manœuvre d’un autre véhicule, au mauvais arrimage d’un
chargement (sac de sport par exemple…).

=== Conclusion

Les motocyclistes doivent connaître leurs limites de compétence,
accepter d’augmenter constamment leur marge de sécurité et intégrer le
fait qu’ils seront toujours les victimes de leurs erreurs ou des erreurs
d’autrui, les automobilistes n’ayant pas toujours intégré ou été formés
à détecter les motocyclistes dans leur recherche d’informations.

[[fiche-3.md]]
== Les facteurs de risque à moto

=== Les facteurs de risque

==== L’alcool, les drogues

* Près d’un motocycliste sur 4 impliqués dans un accident mortel a un
taux d’alcoolémie positif.
* L’usage du cannabis seul multiplie le risque d’être responsable d’un
accident mortel par 1,8.
* L’usage combiné du cannabis et de l’alcool multiplie ce risque par 14.

==== La vitesse excessive

* Plus la vitesse est élevée, plus il est difficile d’éviter un obstacle
ou de faire face à un imprévu et plus les conséquences de la chute ou de
la collision sont importantes.
* L’angle de vision passe de 110° à l’arrêt à 30° à une vitesse de 130
km/h.
* A grande vitesse le regard se porte uniquement dans l’axe de la voie
de circulation.
* En virage le risque de déport de sa voie ou de perte d’adhérence est
plus important entraînant un risque de collision de face ou de sortie de
route.
* Plus la vitesse est élevée, plus la détectabilité d’un motocycliste
est difficile pour les autres usagers.

==== La fatigue

L’hypovigilance touche aussi bien les motocyclistes que les autres
usagers, mais plus rapidement et surtout elle pardonne moins. Avec la
perte d’équilibre, la chute est immédiate.

==== L’illusion de visibilité

Les automobilistes, camionneurs et autres usagers de la route éprouvent
des difficultés à détecter les motocyclistes. De plus, le motocycliste
s’imagine avoir été vu alors qu’il ne l’a pas été.

Avoir la priorité ne suffit pas. C’est d’abord au motocycliste de
prévoir et d’assurer lui même sa sécurité en se rendant détectable, en
s’assurant d’avoir été détecté et en augmentant le plus possible sa
marge de sécurité.

==== L’inexpérience

Le manque de maîtrise des débutants, la reprise de la conduite après un
temps d’arrêt ou la conduite d’une moto dont on n’a pas l’habitude,
couplé généralement à un excès de confiance, voire un sentiment
d’invulnérabilité, sont à l’origine de nombreux accidents.

Près d’un motocycliste sur dix impliqué dans un accident de la route a
moins de six mois d’expérience.

==== L’état de la chaussée

L’adhérence d’une moto est précaire : la surface de contact au sol des
pneumatiques est l’équivalent de la surface d’une carte de crédit…

Marquages au sol, plaques d’égout, chaussée humide ou grasse, chaussée
dégradée, gravillons, feuilles mortes doivent être des indices
recherchés et pris en compte pour adapter sa conduite.

==== La météo

La pluie diminue la visibilité, le vent violent occasionne des écarts de
trajectoire, le froid engourdi les membres et la chaleur peut inciter à
oublier les équipements de protection.

Un temps sec donne confiance et contribue à relâcher la vigilance : plus
de 90 % des décès de motocyclistes ont lieu par beau temps.

==== L’état du véhicule

Le bon état technique de la machine est essentiel. Une vérification
régulière des pneus, freins, feux et niveaux est indispensable.

=== Les facteurs aggravants

L’absence de protection et la présence d’obstacles fixes sont les
principaux facteurs qui contribuent à accentuer la gravité des accidents
impliquant des motocyclistes.

Un équipement de protection n’évite pas l’accident mais permet toujours
d’en diminuer les conséquences:

* Il peut sauver une vie.
* Il peut transformer un blessé grave en blessé léger, et un blessé
léger en personne indemne.
* Le sac à dos pouvant entraîner de graves blessures à la colonne, il
faut lui préférer la valise ou le top-case.

[[fiche-4.md]]
== Prise de conscience des risques

Les motocyclistes ont proportionnellement un nombre plus élevé
d’accidents que les autres usagers de la route.

Si la tâche complexe qu’est la maîtrise d’une moto, et l’absence de
carrosserie expliquent en partie cette forte implication dans les
accidents de la route, le rapport au risque et la recherche de
sensations de certains motocyclistes y participent aussi pour une part
importante.

Il est important pour chacun de prendre conscience des risques
occasionnés par une conduite inadaptée aux besoins et aux circonstances
rencontrées.

Les usages et attitudes des motocyclistes mettent en évidence des
différences de comportement.

Ces différences viennent du fait que chaque motocycliste a sa propre
perception du risque dont l’évaluation reste subjective.

=== Les profils types de motocyclistes

Différentes études (*) ont permis d’établir le profil des motocyclistes
et les risques auxquels ils s’exposent respectivement.

Cela peut relever soit d’une prise de risque délibéré soit d’une
méconnaissance ou inconscience du risque.

Deux groupes et cinq profils répartis à peu près équitablement de 20%
chacun :

==== Premier groupe : la conduite prudente

===== 1. Les modérés

* Usage : moyen de transport secondaire, utilisé les week-ends et en
vacances.
* Motos ``custom''.
* Représentation : un loisir.
* Leur bien-être passe par l’évasion, la recherche de plaisir est plus
importante que la recherche de sensations à travers la vitesse.
* Pas d’infraction particulière.

===== 2. Les stressés

* Usage : uniquement utilitaire, facilité des déplacements.
* Ils ont une faible expérience de la conduite et une préférence pour
les scooters.
* Représentation : un moyen de transport.
* Sentiment d’insécurité : la conduite est une source de stress car ils
ont une conscience aiguë du danger et des accidents possibles.
* Exemple d’infractions commises : circulation sur des voies réservées.

===== 3. Les sereins

* Usage : régulier.
* Représentation : évasion et respect des règles
* Sentiment de responsabilité : le deux-roues est perçu à la fois comme
pratique et source de plaisir, la conduite est responsable.
* Ils ont conscience du danger et respectent le code de la route.
* Pas d’infraction particulière.

==== Second groupe : la conduite à risque

===== 1. Les sportifs

* Usage : passionné, kilométrage annuel élevé.
* Moto de grosse cylindrée, catégorie sportive ou roadster.
* Représentation : sport, évasion, communauté.
* Identité motarde forte, ils sont amateurs de vitesse et recherchent la
maîtrise du risque.
* Sentiment de puissance.
* Exemple d’infractions commises : excès de vitesse.

===== 2. Les transgressifs (deux-roues utilitaires) :

* Usage : utilitaire
* Moto de petite cylindrée et scooters.
* Représentation : un moyen de transport, deux-roues = gain de temps.
* Pas à la recherche de sensation, la moto est utilisée avant tout comme
un objet utilitaire, pour réduire les temps de trajets et éviter les
transports en commun.
* Ne mesurent pas les conséquences de leur comportement.
* Infractions multiples pour gagner du temps : sens interdits, arrêt au
stop non marqué, circulation sur les trottoirs, remontées de file…

(*) Source des études : GEMA et IFSTTAR.

[[fiche-5.md]]
== La conduite préventive

=== Anticipation

Certains signes laissent présager une situation dangereuse. Les
détecter, c’est anticiper le danger et pouvoir l’éviter.

De manière générale il faut :

* se méfier de chaque endroit où il risque d’y avoir un conflit
d’usagers (carrefours, intersections, passages, sorties de chemin,
carrefours à sens giratoire…).
* rester vigilant à l’égard des véhicules qui nous entourent (devant,
derrière, à gauche, à droite), d’où l’importance des rétroviseurs.

=== Adaptation de la vitesse

* La capacité d’accélération d’une motocyclette est bien supérieure à
celle d’une voiture.
* Cette accélération peut surprendre un automobiliste.
* Un piéton qui traverse inopinément, un trou dans la chaussée, des
traces grasses sur la route, un coup de vent, une voiture qui déboîte
sans prévenir…
* Il faut toujours adapter son allure pour pouvoir réagir en cas
d’obstacle imprévu.
* Près d’une cinquantaine d’usagers, tous les ans, décèdent après avoir
été percuté par une moto.

=== Voir et être vu

* Les feux allumés, de jour comme de nuit.
* Une bonne position dans sa voie de circulation.
* Se signaler aux autres usagers, il faut être repéré et vu des
automobilistes. L’absence de détection est relevée dans près des deux
tiers des accidents impliquant une voiture et une moto.
* Etre visible, des vêtements de préférence aux couleurs vives et un
casque clair, munis des bandes rétroréfléchissantes.
* Savoir regarder, le regard détermine la trajectoire, il permet de
détecter les dangers.

=== Respect des distances de sécurité

* Avec une moto, quelle qu’en soit la puissance, le respect des
distances de sécurité est le préalable à toute recherche de sécurité.
* Garder ses distances, c’est se donner du temps de réaction face aux
dangers.
* Il convient de rouler à distance des véhicules en stationnement, en
laissant si possible la largeur d’une portière. L’idéal : 1,50 m.

=== Savoir freiner

* Idéalement, la moto droite.
* Ne pas freiner en virage lorsque la moto est inclinée : elle se
redresserait alors immédiatement en modifiant sa trajectoire de courbe
entraînant un risque de chute ou de sortie de route.
* Ne pas bloquer la roue avant.
* Eviter de bloquer la roue arrière, cela réduit l’efficacité du
freinage.

=== La manœuvre d’évitement

Il est souvent moins dangereux d’esquiver une collision par une manœuvre
d’évitement que de freiner brutalement et de perdre l’équilibre au
freinage.

[[fiche-6.md]]
== L’équipement

=== Le casque : récent, homologué et correctement attaché

Obligatoire pour le motocycliste et son passager, il doit être homologué
(avec obligation de la présence des dispositifs réfléchissants), coiffé
et attaché avec une jugulaire ou verrouillé.

Il doit être conforme :

* soit à la norme européenne : une étiquette blanche. De plus en plus
fréquente (lettre E suivie de l’indication du pays ayant homologué le
casque et du numéro d’homologation)
* soit à la norme française : une étiquette verte NF. Cette norme tend à
disparaître.

Quel que soit le type de casque, 20% sont éjectés en cas d’accident
grave, et cela pour deux causes principales :

* une taille du casque mal adaptée à la tête de l’usager.
* une jugulaire non attachée ou une attache trop lâche ce qui revient au
même en cas de choc.

Il convient de :

* ne jamais l’acheter d’occasion.
* le choisir parfaitement ajusté à sa tête, après avoir mis le casque
sans en serrer la jugulaire, il ne doit pas bouger ni compresser la
tête.
* le fixer avec soin, la sangle devant toujours être correctement
attachée et serrée.
* veiller à la qualité antirayures et antibuée de la visière, pour
s’assurer une parfaite visibilité.
* remplacer son casque obligatoirement après tout impact violent.

=== La tenue

Le blouson protège non seulement des intempéries et du froid, mais aussi
et surtout en cas de chutes et de glissades éventuelles.

Il contribue également à rendre plus visible.

Seul un vêtement adéquat peut contribuer à éviter fractures, contusions
et autres très graves brûlures par abrasion.

Toute tenue légère en moto est à proscrire. Les doublures en matières
synthétiques de type nylon sont à éviter absolument. En cas de glissade,
elles fondent sur la peau entraînant alors de très graves blessures par
brûlure, difficiles à traiter, avec des conséquences parfois
irréparables pour les tissus.

L’idéal :

* un blouson certifié équipement de protection individuelle (EPI),
renforcé au niveau des coudes et des épaules, certains sont aussi
équipés d’une protection dorsale, d’un airbag, d’autres sont
imperméabilisés et équipés d’une doublure amovible matelassée….
* du cuir ou des textiles anti-abrasion pour protéger les zones du corps
les plus exposées aux brûlures en cas de chute.

=== Les gants et les chaussures

==== Les gants :

Le beau temps n’empêche pas les coupures, les contusions et les brûlures
par abrasion en cas d’accident. La conduite d’une moto sans gants est
donc à proscrire, quelles que soient les saisons et la météo.

Les blessures causées par l’absence du port des gants peuvent engendrer,
même à faible vitesse, des conséquences irréparables et aussi des
handicaps permanents (amputations, paralysies…).

Indépendamment des questions de sécurité en cas de choc, les gants
permettent aussi de protéger du froid ou de l’humidité.

L’idéal : des gants, certifiés EPI, en cuir renforcés aux articulations
et à la paume et pourvus d’une patte de serrage permettant leur parfait
maintien en cas de glissade.

==== Les chaussures :

Les pieds, chevilles et tibias sont des zones du corps particulièrement
exposées, notamment dans les nombreux cas d’impacts latéraux et de
chutes.

A défaut de bottes spécifiques à la moto avec renforts (idéales bien
sûr), des chaussures en cuir, solides et montantes sont nécessaires pour
protéger les chevilles.

Les talons hauts et fins mais aussi les chaussures basses, dénuées de
protection des chevilles, sont à proscrire, de même que les sandales ou
les tongs. Les blessures peuvent être irréparables…

[[fiche-7.md]]
== Les éléments mécaniques du motocycle liés à la sécurité

=== Les pneumatiques

Seuls points de contact et d’adhérence avec la chaussée, les
pneumatiques sont essentiels.

Ils sont les premiers garants de la qualité du freinage.

Les témoins d’usure sont à surveiller régulièrement. Dès que ces témoins
sont atteints, les pneus sont à changer d’urgence.

La juste pression conditionne la sécurité et le confort de conduite.

Chaque constructeur et manufacturier édite un tableau de pression et
établit ses recommandations, avec des niveaux de pressions souvent
différenciés pour les pneus avant et arrière auxquels il faut se
référer.

Le surgonflage accélère l’usure du pneumatique et défavorise la tenue de
route sur chaussée détrempée.

Un sous-gonflage important :

* déstabilise le motocycle, quelle que soit la vitesse de circulation.
* entraîne des risques de dérapages plus importants.

=== Les freins

Les freins constituent la première des assurances sur la route et leur
parfait état de fonctionnement est fondamental pour la sécurité.

En cas de danger la première réaction est de solliciter les freins, ils
sont le système de défense privilégié pour tous les usagers de la route.

Un système ABS permet en cas de freinage d’urgence de conserver la
maîtrise de la trajectoire et la stabilité de sa machine sans raccourcir
la distance d’arrêt mais en l’optimisant.

L’état des disques, du liquide de frein et l’usure des plaquettes sont à
vérifier très régulièrement.

Dès que nécessaire il convient de faire changer les plaquettes de
freins, d’autant plus important qu’il en va de l’usure prématurée du
disque de frein.

=== Les feux

Pour rendre visible les motocyclistes des autres catégories d’usagers
l’allumage des feux de croisement est obligatoire (code de la route).

Les feux doivent être homologués. Il convient de vérifier régulièrement
leur propreté et leur fonctionnement.

L’importance du clignotant :

La panne d’un clignotant en moto constitue un réel danger, d’autant que
l’on peut ne pas s’en apercevoir tout de suite.

La vérification de leur bon fonctionnement est donc à inclure donc dans
son check-up quotidien.

=== Niveau des liquides du moteur

Les liquides (freins, huile et carburant) constituent des facteurs
centraux de la bonne ``santé'' de la moto.

Pour ces vérifications, il faut utiliser la notice du constructeur afin
de ne rien oublier et de respecter les directives qu’elle contient.

On peut demander conseil à son garagiste pour s’assurer des bons délais
de vérifications (par exemple, le liquide de frein est généralement à
remplacer au moins tous les deux ans).

Rouler avec une carence d’huile moteur peut occasionner un ``serrage
moteur'' et causer d’importants dommages à une moto et surtout entraîner
un danger réel :

* chute, percussion par l’arrière, projections de fluides brûlants, etc.

=== Les modifications techniques

Il est interdit de modifier sans autorisation :

* le dispositif d’échappement.
* le type de transmission.
* la cylindrée, le taux de compression et la puissance.
* si adjonction d’un side-car, modification obligatoire du certificat de
réception.
* le diamètre des roues.

[[fiche-8.md]]
== L’assurance

=== Les différents types

Il existe deux principales sortes d’assurances : L’assurance obligatoire
et les assurances facultatives.

==== L’assurance obligatoire :

C’est ce qu’on appelle habituellement l’assurance ``aux tiers''.

Elle garantit la responsabilité civile du motocycliste et paie les
dommages causés aux autres, elle n’indemnise ni les dégâts causés à sa
moto ni ses dommages corporels.

Le motocycliste doit obligatoirement être assuré en responsabilité
civile pour les dommages causés aux tiers.

Ces dommages peuvent avoir une origine accidentelle, provenir d’un
incendie de la moto, voire même de la chute des objets qu’elle
transporte.

La garantie de responsabilité civile s’applique à toute personne
autorisée à conduire la moto assurée.

==== Les assurances facultatives :

Le motocycliste est libre de les souscrire ou non en plus de l’assurance
obligatoire.

Elles offrent les garanties suivantes :

* la garantie ``dommage collisions'' ou ``tiers-collisions'' indemnise
les dégâts causés au véhicule de l’assuré même s’il est responsable, en
cas de collision avec un autre usager identifié.
* la garantie dommage par accident indemnise les dégâts causés au
véhicule de l’assuré, même s’il n’y a pas eu de collision. Cette
garantie est souvent appelée ``tous risques''.
* la garantie individuelle accident couvre l’assuré lui-même en cas de
blessure, l’assurance verse une certaine somme. en cas de décès elle
verse une somme d’argent aux héritiers.
* la garantie vol-incendie rembourse la valeur du véhicule, déduction
faite de la franchise en cas de vol ou incendie du véhicule.
* la garantie défense-recours prend en charge, sous certaines
conditions, la défense de l’assuré en cas d’accident ou d’infraction ou
négocie avec l’adversaire en cas d’accident afin d’obtenir la meilleure
indemnisation possible de l’assuré.

=== Les conséquences d’un défaut d’assurance

L’absence d’assurance constitue une infraction passible, notamment,
d’une amende et d’un emprisonnement.

En cas d’absence d’assurance, le motocycliste responsable d’un accident
devra payer tous les dommages causés :

* aux autres véhicules.
* au domaine public (poteaux, plantations, etc.).
* au domaine privé.
* aux victimes (blessés ou tués), les soins, hospitalisation,
traitements, rentes…, ces frais peuvent représenter des sommes très
importantes.

=== Les cas de refus de payer par l’assureur

* Dommage volontairement causé par l’assuré.
* Le motocycliste est sous l’emprise d’un état alcoolique.
* Le motocycliste n’a pas l’âge requis.
* Le motocycliste n’est pas titulaire du permis correspondant à la
catégorie de la moto utilisée.
* le permis n’est pas en état de validité (suspension, retrait, visite
médicale…).
* Transformation(s) qui modifie(nt) les caractéristiques techniques
indiquées sur le certificat d’immatriculation (débridage par exemple).
* Déclaration frauduleuse lors de la souscription du contrat.

[[fiche-9.md]]
== L’alcool, les stupéfiants

=== L’alcool

Les accidents moto imputables à l’alcool en 2011 (Source ONISR) :

* 1 accident mortel sur 4.
* 151 décès.
* Ils ont lieu 1 fois sur 2 la nuit.

=== L’alcoolémie

Le taux d’alcool limite à ne pas atteindre est de 0,5 g d’alcool par
litre de sang soit 0,25 mg d’alcool par litre d’air expiré.

Chaque verre (norme débit de boisson) consommé fait monter le taux
d’alcool de 0,20 g à 0,25 g en moyenne.

Ce taux peut augmenter en fonction de l’état de santé, du degré de
fatigue, du stress ou des caractéristiques physiques de la personne.

Le taux d’alcool maximal est atteint :

* 1/2 heure après absorption à jeun.
* 1 heure après absorption au cours d’un repas.
* L’alcoolémie baisse en moyenne de 0,10 g à 0,15 g d’alcool par litre
de sang en 1 heure.
* Café salé, cuillerée d’huile… : aucun ``truc'' ne permet d’éliminer
l’alcool plus rapidement.

=== Les effets

L’alcool agit sur le cerveau et sur tout le système nerveux, ce qui
provoque des conséquences graves pour le conducteur.

Les conditions physiques sont amoindries :

* champ visuel réduit, vision trouble, inattention, sommeil.
* perte de mémoire, perte des apprentissages, diminution des réflexes.

Le comportement est modifié :

* diminution de la peur et prise de risque exagérée.
* agressivité.
* euphorie.

=== Le cannabis

Les effets :

* capacité à contrôler la trajectoire diminuée.
* temps de réaction allongé.
* déficit des mécanismes d’attention et de vigilance.
* fausse sensation de sécurité.

L’usage du cannabis seul multiplie le risque d’être responsable d’un
accident mortel par 1,8.

L’usage combiné du cannabis et de l’alcool (alcoolémie positive)
multiplie ce risque par 14.

=== Les médicaments

Un grand nombre de médicaments souvent appelés anodins présentent des
effets indésirables pouvant influencer l’aptitude à conduire sans que le
conducteur en soit conscient.

Avant de conduire, il convient de lire attentivement les notices ou de
demander conseil à son médecin.

Certains médicaments sont incompatibles avec la consommation d’alcool et
entraînent un sur-risque d’accident considérable.

=== Les sanctions

==== L’alcool :

Taux compris entre 0,5 et 0,8 g (contravention) :

* amende de 135 euros et retrait de 6 points sur le permis de conduire.

Taux égal ou supérieur à 0,8 g (délit) :

* retrait de 6 points sur le permis de conduire.
* amende pouvant aller jusqu’à 4 500 euros.
* immobilisation du véhicule.
* suspension (jusqu’à 3 ans) voire annulation du permis.
* peine de prison (jusqu’à 2 ans).

==== Les stupéfiants :

Des dépistages d’absorption de substances ou plantes classées comme
stupéfiants sont réalisées par les forces de police et de gendarmerie.

En cas de dépistage positif et confirmé :

* retrait de 6 points sur le permis de conduire.
* amende pouvant aller jusqu’à 4 500 euros.
* immobilisation du véhicule.
* suspension (jusqu’à trois ans) voire annulation du permis.
* peine de prison (jusqu’à deux ans).

Les sanctions sont aggravées lorsque cette infraction est couplée avec
un taux d’alcool prohibé : les peines sont portées à trois ans
d’emprisonnement et 9 000 euros d’amende.

[[fiche-10.md]]
== La fatigue et la route de nuit

=== Fatigue et somnolence

La fatigue et la somnolence augmentent considérablement le risque
d’accident.

Pour un motocycliste la vigilance et l’efficacité sont primordiales.

==== La fatigue

C’est la difficulté à rester concentré.

Ses signes :

* les yeux picotent.
* le cou et les épaules sont raides et font un peu mal, sensation d’être
mal assis.
* douleurs de dos.
* regard qui se fixe.

Ses effets :

* les gestes et le regard sont moins efficaces.
* les réactions et les réflexes sont plus lents.

==== La somnolence

C’est la difficulté à rester éveillé.

Ses signes :

* bâillements.
* paupières lourdes.

Ses effets :

* une tendance à prendre des risques pour arriver plus rapidement.
* une forte envie de dormir.
* endormissement.

Dès les premiers signes, il faut s’arrêter car les risques d’avoir un
accident dans la demi-heure qui suit sont augmentés.

Solutions :

* bien se reposer avant le départ.
* s’alimenter normalement, mais sans excès.
* ne pas absorber d’alcool.
* adapter sa vitesse aux circonstances, une vitesse excessive induit une
fatigue supplémentaire.
* s’arrêter régulièrement pour se reposer (conseillé toutes les heures).

=== La route de nuit

3 décès de motocyclistes sur 10 ont lieu la nuit.

Ces accidents nocturnes sont la conséquence d’une vitesse supérieure, du
manque de visibilité, de la fatigue et surtout de l’absorption d’alcool.

Les précautions à prendre :

Avant le départ :

* contrôler le bon état, la propreté, le réglage et le bon
fonctionnement des feux.
* le bon état de la batterie.
* s’équiper de manière à être protéger du froid et de l’humidité, à
mieux voir et être vu (écran du casque et/ou lunettes propres, vêtements
munis de dispositifs rétroréfléchissants).

Pendant le trajet :

* faire des pauses plus fréquentes.
* adapter son allure à la visibilité.
* ralentir davantage en virage que le jour, car l’importance de la
courbe est plus difficile à apprécier et la perception des obstacles
plus tardive.
* en cas d’éblouissement, fixer le bord droit de la route le plus loin
possible.
* se méfier du ``coup de pompe'' au petit matin.

[[fiche-11.md]]
== Vitesse et freinage

=== Vitesse en mètres par seconde

Exprimée verbalement en kilomètres à l’heure, il est plus intéressant de
la calculer en mètres par seconde car la distance d’arrêt se mesure en
mètres et non en kilomètres,

Pour calculer la distance parcourue en une seconde, il suffit de
multiplier par 3 le chiffre des dizaines de la vitesse indiquée.

Exemple :

* à 50 km/h : 5 × 3 ≈ 15 m/s.
* à 90 km/h : 9 × 3 ≈ 27 m/s.

=== Le temps de réaction

C’est le temps qui s’écoule entre la perception de l’obstacle et
l’action sur les freins (environ 1 seconde) au cours duquel la moto
n’est pas freinée et continue à avancer.

Ce temps peut être plus important si le motocycliste est :

* fatigué ou malade.
* sous l’effet de l’alcool, de la drogue ou de certains médicaments.
* distrait ou soucieux.

=== L’énergie cinétique

C’est l’énergie qui animait le ou les véhicules juste avant le choc.

Après le choc, véhicule(s) immobilisé(s), l’énergie cinétique est tombée
à zéro, car elle a été ``consommée'' en déformations mécaniques très
brutales.

Elle augmente avec la masse du véhicule et le carré de la vitesse :

Percuter un obstacle à 50 km/h à moto revient à tomber de trois étages.

Percuter un obstacle à 90 km/h à moto revient à tomber de dix étages.

Percuter un obstacle à 130 km/h à moto revient à tomber de vingt-deux
étages.

=== La distance de freinage

C’est la distance parcourue lorsque les freins sont en action.

La distance de freinage dépend de l’état de la route, des pneumatiques,
de l’état et de l’utilisation des freins, des réactions de la moto.

Cette distance est proportionnelle au carré de la vitesse.

Route sèche :

* à 50 km/h ≈ 15 m.
* à 90 km/h ≈ 50 m.
* à 130 km/h ≈ 110 m.

On considère que la distance de freinage sur route mouillée est
multipliée par deux.

=== Les distances d’arrêt et la vitesse

La distance d’arrêt est égale à la distance parcourue pendant le temps
de réaction, plus la distance parcourue pendant le freinage.

On peut effectuer un calcul approximatif de la distance d’arrêt en
multipliant le chiffre des dizaines de la vitesse indiquée par lui-même
:

Exemple :

* à 90 km/h, on obtient : 9 × 9 ≈ 81 m de distance d’arrêt.
* à 130 km/h, on obtient : 13 × 13 ≈ 169 m de distance d’arrêt.

=== Freinage et réaction de la moto

Lors de l’utilisation du frein avant, la fourche télescopique s’enfonce,
absorbe la charge sur l’avant et évite au pilote de passer par dessus le
guidon.

Il est impératif de doser et de répartir le freinage (environ 70 % à
l’avant et 30 % à l’arrière).

L’utilisation du frein arrière permet ``d’asseoir'' la machine sur la
roue arrière et de limiter le transfert de charge sur la roue avant.

Lors d’un freinage d’urgence, il est préférable d’anticiper légèrement
sur le frein arrière afin d’éviter le délestage de la roue arrière et
limiter le transfert de charge sur la roue avant.

=== Freinage et dérapage

Le freinage est la manœuvre la plus fréquemment tentée en situation
d’urgence. Mais plus le freinage est brutal et soudain, plus la
difficulté de maîtriser sa moto est élevée.

En situation d’urgence 1 motocycliste sur 5 chute.

En cas de blocage de roue, relâcher la pression pour retrouver
l’efficacité du freinage et le contrôle de la direction.

L’idéal : être équipé d’un système ABS.

[[fiche-12.md]]
== Stabilité et trajectoire

=== L’effet gyroscopique

La rotation d’une roue engendre un phénomène, appelé effet gyroscopique,
qui permet de maintenir la roue en équilibre.

Cet effet s’oppose à la modification de l’axe de rotation du moyeu de la
roue.

Pour vaincre cet effet (en virage par exemple), il faut exercer sur le
guidon un effort d’autant plus important que l’allure est élevée
(inclinaison de la machine).

=== Le contre-braquage

Le contre-braquage, ou braquage inverse, est une technique qui permet de
négocier correctement un virage à allure soutenue ou même d’éviter un
obstacle soudain (uniquement à vitesse élevée) : il s’agit d’amorcer le
changement de direction par une bascule de la moto vers l’intérieur du
virage à prendre. On provoque cette bascule par une brève action sur le
guidon.

L’action consiste à pousser sur le guidon ainsi :

* pour un virage à gauche, pousser sur la partie gauche.
* pour un virage à droite, pousser sur la partie droite.

=== La force centrifuge

C’est la force qui, dans un virage, entraîne la moto vers l’extérieur de
la courbe. Le motocycliste doit la vaincre par une poussée sur le
guidon.

* Elle est proportionnelle au carré de la vitesse.
* Plus la motocyclette est chargée (passager ou bagages), plus la force
centrifuge augmente.
* Plus le virage est serré, plus la force centrifuge augmente.
* Pour compenser les effets de la force centrifuge, il faut incliner la
machine vers l’intérieur du virage.

Cette technique ne peut être efficace que si la vitesse est adaptée au
rayon de la courbe.

=== L’évitement

Il est souvent moins dangereux pour un motocycliste d’esquiver une
collision par une manœuvre d’évitement que de freiner brutalement et de
perdre l’équilibre au freinage.

Si la manœuvre d’évitement semble plus efficace que le freinage, sa
réalisation s’avère plus difficile.

A 50 km/h, il est possible de faire un évitement, à partir de 70 km/h,
sa mise en œuvre devient compliquée et exigeante.

=== Les virages à moto

==== Visibilité :

Avant d’aborder un virage, il faut avoir évalué :

* l’importance de la courbe (à droite ou à gauche).
* l’état et la largeur de la chaussée.
* la présence d’autres usagers.

==== Vitesse :

Il faut adapter sa vitesse en fonction :

* de la visibilité.
* du rayon de la courbe.
* de l’état du sol.
* du chargement de la moto.

==== Trajectoire :

* adapter sa vitesse (décélération et rétrogradage avant le virage).
* pour la découverte du virage, placer sa machine à droite pour un
virage à gauche, près de l’axe médian pour un virage à droite.
* plonger vers l’intérieur de la courbe (point de corde).
* terminer en reprenant sa position dans la voie.

Attention : la faible garde au sol des scooters, du fait de la taille
réduite des roues, entraîne un risque accru de chute en virage.

[[fiches-interrogations.md]]
== Fiches d’examen

=== Fiche 1 : Le risque routier moto/comportement en présence d’un accident

* Le risque routier moto.
* Les accidents mortels en moto.
* Gravité.
* Comportement en présence d’un accident.

=== Fiche 2 : Les accidents les plus caractéristiques

* Accidents en collision
* Accidents en solo

=== Fiche 3 : Les facteurs de risque à moto

* Les facteurs de risque.
* Les facteurs aggravants.

=== Fiche 4 : Prise de conscience des risques

* Les profils types de motocyclistes.
* La conduite prudente.
* La conduite à risque.

=== Fiche 5 : La conduite préventive

* Anticipation.
* Adaptation de la vitesse.
* Voir et être vu.
* Respect des distances de sécurité.
* Savoir freiner.
* La manœuvre d’évitement.

=== Fiche 6 : L’équipement

* Le casque.
* La tenue.
* Les gants et les chaussures.

=== Fiche 7 : Les éléments mécaniques du motocycle liés à la sécurité

* Les pneumatiques.
* Les freins.
* Les feux.
* Les niveaux.
* Les modifications techniques.

=== Fiche 8 : L’assurance

* Les différents types.
* L’assurance obligatoire.
* Les assurances facultatives.
* Les conséquences d’un défaut d’assurance.
* Les cas de refus de payer par l’assureur.

=== Fiche 9 : L’alcool, les stupéfiants

* L’alcool.
* L’alcoolémie.
* Les effets.
* Le cannabis.
* Les médicaments.
* Les sanctions.

=== Fiche 10 : La fatigue et la route de nuit

* La fatigue.
* La somnolence.
* Solutions.
* La route de nuit.

=== Fiche 11 : Vitesse et freinage

* Vitesse en mètres par seconde ?
* Le temps de réaction ?
* L’énergie cinétique ?
* La distance de freinage ?
* Les distances d’arrêt et la vitesse ?
* Freinage et réaction de la moto ?
* Freinage et dérapage ?

=== Fiche 12 : Stabilité et trajectoire

* L’effet gyroscopique
* La force centrifuge
* Le contre-braquage
* L’évitement
* Les virages en moto

[[verifications-techniques.md]]
== Vérifications techniques

Ces fiches ne détaillent pas ce que vous devez faire pendant l’examen.
Chacune des actions est dépendante de la moto sur laquelle vous faites
votre apprentissage.

=== Fiche 1

==== Commandes

[arabic]
. Mise en marche du moteur
* Le candidat met en marche le moteur, contrôle l’extinction des témoins
d’alerte et arrête le moteur à l’aide du coupe-circuit (arrêt
d’urgence).
. Commandes d’embrayage et d’accélération
* Si la motocyclette utilisée est à embrayage mécanique : le candidat
vérifie que le câble est non effiloché et que le d’accélération réglage
de la garde est correct (5 mm environ).
* Si la motocyclette utilisée est à embrayage hydraulique : il indique
le point de contrôle du niveau.
* Accélérateur : le candidat vérifie la bonne rotation de la poignée y
compris à la décélération (retour de la poignée).

==== Éléments techniques

[arabic]
. Niveau d’huile moteur
* Le candidat explique la façon de procéder et indique à l’expert le
point de contrôle.
* Véhicule à carter humide : la moto doit être droite ou sur la béquille
centrale (ne pas exiger cette position).
* Véhicule à carter sec : il faut faire tourner le moteur au ralenti 2
minutes environ et contrôler immédiatement dès l’arrêt du moteur.
. Transmission
* A chaîne : le candidat contrôle la tension de la chaîne en indiquant
la flèche et la position de la moto préconisées par le guide
d’utilisation.
* A cardan : il indique le point de contrôle du niveau d’huile.
* A courroie : il contrôle l’état de la courroie.

==== Éclairage et accessoires de sécurité

[arabic]
. Eclairage avant
+
Le candidat vérifie le bon état du ou des optiques et le bon
fonctionnement des feux de position, croisement, feux de route.
. Indicateurs de changement de direction
+
Le candidat vérifie le bon état et le bon fonctionnement des indicateurs
de changement de direction.

=== Fiche 2

==== Commandes

[arabic]
. Direction
+
Le candidat explique comment il contrôle l’absence de jeu dans la
direction sans effectuer l’opération : il faut délester la roue avant et
faire tourner le guidon de gauche à droite. Il ne doit pas y avoir de
point de résistance.
. Commandes de frein
* Avant : il contrôle le niveau. Pour effectuer ce contrôle, le
réservoir de liquide de frein doit être à l’horizontale.
* Arrière : Commande mécanique : il contrôle l’usure à l’aide du repère
prévu à cet effet.
* Arrière : Commande hydraulique : il contrôle le niveau.

==== Éléments techniques

[arabic]
. Pneumatique, avant ou arrière
+
Le candidat contrôle le bon état des flancs (pas de déchirure ni de
hernie), de la bande de roulement (sculptures apparentes) et si la
pression de gonflage paraît visuellement correcte.
. Suspensions
* A l’avant dans le cas d’une suspension hydraulique : l’absence de
fuite au niveau des joints à lèvres (ou de leur protection) de la
fourche télescopique.
* A l’avant dans le cas d’une suspension pression d’air : l’absence de
fuite au niveau des joints à lèvres (ou de leur protection). il indique
la valve servant à l’évacuation ou au complément de pression d’air. Il
doit indiquer la valeur de la pression admissible (voir guide
d’utilisation).
* A l’arrière : il indique où s’effectue le réglage.

==== Éclairage et accessoires de sécurité

[arabic]
. Éclairage arrière et feu stop
+
Il contrôle le bon état et fonctionnement de l’éclairage arrière (plaque
comprise) et du feu stop, avec les commandes de frein avant et arrière.
. Avertisseur sonore et rétroviseurs
+
Il vérifie le bon fonctionnement de l’avertisseur sonore, la présence,
le bon état et la fixation correcte des deux rétroviseurs.
